mimiro-io/datahub

internal/server/garbagecollector_test.go

and adjust gc test to query-fix

fix merge error (duplicate count function) 

---

internal/jobs/job.go

Success and failrate of jobs has been added to the metrics reporter.

[ENHANCEMENT] #26 Add success/failure job rate

---

.github/workflows/benchmark.yml
Makefile
dataset_http_integration_test.go
go.mod
go.sum
internal/content/content.go
internal/content/content_test.go
internal/jobs/scheduler.go
internal/jobs/scheduler_test.go
internal/jobs/sink.go
internal/jobs/transform.go
internal/security/dljwt.go
internal/server/dataset.go
internal/server/dataset_benchmark_test.go
internal/server/dsmanager.go
internal/server/dsmanager_test.go
internal/server/store.go
internal/server/streamparser.go
internal/server/streamparser_test.go
internal/web/contenthandler.go
internal/web/datasethandler.go
internal/web/middlewares/authentication.go
internal/web/middlewares/opa.go
internal/web/queryhandler.go
last_bench.txt

Closes Issue #30 
also add new github workflow to run a benchmark test for StoreEntities, and add benchmark results as pull request  comment.

use "github.com/goccy/go-json"

---

.github/workflows/benchmark.yml
Makefile
internal/server/dataset_benchmark_test.go
internal/server/store.go
last_bench.txt

This PR disables conflict detection in badger to improve write performance.
This change also adds a benchmark for dataset.StoreEntities and a github actions pipeline to run it in pull requests.

Disable badger DetectConflicts option

---

go.mod
go.sum
internal/server/dataset.go
internal/server/store_test.go
last_bench.txt

fixed storeEntities to correctly mark rels as deleted when entity is deleted

fix to ensure deleted entity rels are gone

---

internal/web/datasethandler.go

This should fix the issue reported in #38

Return error response when dataset exist #48

---

internal/server/dsmanager.go

Closes Issue #42 and Issue #55.

avoid concurrent read/write to deletedDatasets map

---

internal/web/middlewares/authentication.go

When I started the task, I discovered that the lib was already updated,
however there was still a couple of cleanups in the authentication setup
that needed to be done, so I did those as well.
The most important change is the cleanup of the error handling in the
validation func, as a failure to validate the PEM kinda swallowed it's
error. It would still fail further down, as the certificate would then be
invalid, however, it is much cleaner to handle it properly.
Also moved the alg check inside the jwt parser instead of doing it myself.

[FEATURE] #71 Upgrade vulnerable jwt lib

---

Dockerfile

go 1.17 comes with substantial performance improvements.
https://golang.org/doc/go1.17#compiler

upgrade to go 1.17

---

Dockerfile

accidentally removed in previous change

reintroduce rsync

---

internal/conf/config.go
internal/conf/environment.go
internal/server/store.go

In environments with little memory it can be desirable to use smaller files

introduce option to configure value log file size

---

internal/jobs/scheduler.go

Title,
Tags,
Description
will be added to job

add more job attributes to job struct

---

app.go
dataset_http_integration_test.go
internal/conf/config.go
internal/conf/environment.go
internal/security/claims.go
internal/security/login_provider.go
internal/security/login_provider_test.go
internal/security/manager.go
internal/security/manager_test.go
internal/security/nodeprovider.go
internal/security/token.go
internal/server/backup.go
internal/server/events_test.go
internal/web/datasethandler.go
internal/web/middleware.go
internal/web/middlewares/authentication.go
internal/web/middlewares/authorization.go
internal/web/securityhandler.go
security_integration_test.go

This is a significant update that adds PKI node to node security and local ACL and authorisation capabilities.

Node security

---

internal/jobs/pipeline_test.go
internal/server/dataset.go

add support for list of refs

---

DOCUMENTATION.md
go.mod
go.sum
internal/jobs/pipeline_test.go
internal/jobs/scheduler.go
internal/jobs/source/source.go
internal/jobs/source/union_source.go
internal/jobs/source/union_source_test.go

Issue 134: add union dataset source

---

internal/jobs/pipeline_test.go
internal/jobs/scheduler.go

According to documentation, items in the datasetSources list of a UnionDatasetSource must be DatasetSource config objects.

union datasources format as documented

---

internal/jobs/pipeline_test.go
internal/jobs/sink.go
internal/jobs/source/dataset_source.go
internal/jobs/source/union_source.go

Closes #140 
Testing showed that the main cause for panics was missing dataset sinks.

add dataset existence checks where missing in datasetSink

---

internal/security/nodeprovider.go
security_integration_test.go

also extend test for working nodeSecurity in jobs with actual test run

prevent panics in nodeSecurity support for httpDatasetSource

---

internal/server/dsmanager.go
internal/server/dsmanager_test.go
internal/server/store.go
internal/web/datasethandler.go

`curl -XPATCH -d '{"ID":"new_name"}' http://datahub-hostname/datasets/dataset_name`
DOCUMENTATION.md uses CLI examples rather than direct API calls, to it should be updates separately once the CLI has support for dataset update.

add dataset rename feature

---

go.mod
go.sum
internal/jobs/transform.go
internal/jobs/transform_test.go

Also refactor code to be less ambiguous

Add config to set time out on httptransform

---

DOCUMENTATION.md

Needed to release httptransform

Updated docs for transforms

---

DOCUMENTATION.md
Dockerfile
internal/jobs/transform.go

feature_175: add support for NewEntityFrom

---

internal/server/streamparser.go
internal/server/streamparser_test.go

in cases where consumed batches are invalid (e.g. incomplete, closing elements of the json structure missing), datahub would still consume them without error. This additional check makes json parsing more correct

json parser looks for closing bracket now

---

.github/workflows/docker-image.yml

updated workflow action to work with tags starting with v.

Moved to support tags for version of the form vx.y.z

---

internal/server/statistics.go

a couple improvements to reduce allocations and to avoid loading actual values into memory.
since statistics still can take some time, depending on size of data stored, the endpoints now also regularly emit spaces to the response before the final json is written - this can help to keep the request alive when using cloud gateways and reverse proxies that otherwise would kill the connection due to inactivity.

statistics: improve counting efficiency

---

internal/server/constants.go
internal/service/dataset/lineage.go
internal/service/dataset/lineage_test.go
internal/web/lineagehandler.go
internal/web/web.go

closes #325 
the endpoints are `/lineage` and `/lineage/<dataset>`

implement new lineage API endpoints and tests

---

internal/jobs/concurrent_contextual_store_test.go

test is skipped, but can be run if needed

add load test for contextual store usage

---

internal/jobs/pipeline_test.go
internal/jobs/transform.go
internal/server/store.go

add txn.AssertDataset
