mimiro-io/datahub

internal/jobs/pipeline_test.go
internal/jobs/raffle.go
internal/jobs/scheduler_test.go
internal/server/dsmanager_test.go
internal/server/events_test.go

and remove usage of time.Sleep to improve test robustness.
Fixes #2 
In this fix, the tests are overriding a statsd `ClientInterface`.
Since the raffle system reports to statsd, we are able to hook waitgroups in right before and after asyncronous job exectutions. This allows the tests to wait for async jobs without time.Sleep() and should therefore much less dependent on hardware specifics.

utilize statsd as job state recorder

---

internal/server/dataset.go
internal/server/store.go
internal/server/store_test.go

outgoing refs were being hidden by later version of the same entity in another dataset
some incoming refs were getting wrongly marked as deleted when storing the same entity in another dataset
point in time queries for inverse relationships was broken
NOTE: the binary representation has not changed, but some inverse rels may be marked as deleted when they are not. it is recommended to delete and reload the affected datasets.

fixed query issues

---

internal/jobs/sink.go

The http sink is missing it's content-type, so added it.
This is considered a bug, and is currently breaking Spring Boot based
datalayers.

BUGFIX: Add Content-Type header to http sink

---

internal/jobs/scheduler.go
internal/server/events_test.go

If the type is unchanged, they will be re-registered
Closes issue #8

unregister event jobs before they are re-added

---

internal/server/error.go
internal/web/contenthandler.go
internal/web/datasethandler.go
internal/web/jobshandler.go
internal/web/queryhandler.go

When the datahub is accessed with it's web api, it is currently hard to tell what went  wrong if the user sends invalid input data. This is because the web handler return generic error messages. 
This can be improved by appening the underlying error messages to the respones.
Example, when sending an empty payload to a dataset:

more detailed error messages in API responses

---

internal/server/dataset.go
internal/server/dsmanager_test.go
internal/server/store.go

If a dataset was deleted, followed by a GC (datahubs own deleteEntities gc), the write performance to the same keys that have been previously deleted suffered greatly. We could pin it down to reverse badger iterators. If used normally, they would be up to 100 times slower after a delete. If the iterator was used with an `AllVersions=true`, the performance was normal. Also forward iterators performed as expected.
This Change tries to solve the performance issues after deletes by not using iterators in StoreEntities at all.
We also raise the MemTableSize option of badger to 128M (from 64M)

replace use of reverse iterators in StoreEntities

---

DOCUMENTATION.md
internal/jobs/transform.go
internal/jobs/transform_test.go
last_bench.txt

Some of the transform functions were a little bit wonky, and some useful
functions were also missing.
All JavaScript functions have been updated to prevent erroring when missing
values, either entities or fields or properties. Functions returning values
are now all returning undefined if no value can be found, rather than a mix
of null and undefined (this should have no impact, as before they would
just crash).
* SetProperty(entity, prefix, name, value) - no longer crash
* GetProperty(entity, prefix, name, defaultValue) - no longer crash, optional default value
* AddReference(entity, prefix, name, value) - no longer crash
* GetId(entity) - no longer crash
* SetId(entity, id) - new
* SetDeleted(entity, deleted) - new
* GetDeleted(entity) - new
* RenameProperty(entity, originalPrefix, …

[FEATURE] Update transform functions #36

---

internal/jobs/job.go
internal/jobs/source.go
internal/jobs/transform.go
internal/jobs/transform_test.go
internal/server/dataset.go
last_bench.txt

The noticable change here is the timeout removal in httpDatasetSource.
The way a pipeline ties source, transform and sink together makes progress in the source dependent on writes in the sink. If our sink writes are blocked for some reason (e.g. badger compaction), we currently would hit source timeouts.
Instead of adjusting the source timeouts higher, we want to operate without timeout here. Most or all operations in the source-reading loop (mainly the streamparser) should throw errors if the connection breaks so that we should be able to avoid lockups without timeouts.
----
This change also adds and changes some metrics:
- `jobs.success`, `jobs.error` have been changed to report job runtime. `jobs.cancelled` was added as well. This allows for graphing of runtime durations over time. …

remove timeout constrains in httpDatasetSource. And add metrics

---

internal/server/store_test.go
last_bench.txt

The tests covering dataset scopes were previously written as a matrix test. While it did it's job, it was always hard to revisit the tests and understand what they were about.
This change refactors theses tests  as common goblin cases for improved readablility. Functionality and coverage should be unchanged.

rewrite matrix test in terms of goblin framework

---

internal/jobs/transform.go
internal/server/dataset.go

Timing transmits more timeseries-data per metric, and therefore gives more granular insight than sums of durations.

use statsd.Timing instead of Count.

---

internal/jobs/raffle.go

currently, event jobs do not decrease the ticket counts for their respective jobTypes. However - they do return tickets and therefor unwillingly increase ticketlimits.
This change lets event job runs decrease the ticket counters just as scheduled jobs.

do not exclude event jobRuns from ticket limits any more

---

DOCUMENTATION.md
internal/jobs/pipeline.go
internal/jobs/transform.go
internal/jobs/transform_test.go

This change introduces 3 more new timing metrics: 
`pipeline.source.batch`
`pipeline.transform.batch`
`pipeline.sink.batch`
These metrics measure the time it takes to process a complete batch in source, transform and sink.
---
This PR also adds a `Timing` transform function, which is available to javascript transforms. It is used like this in javascript:
```
Timing('firstQuery')
var queryResult = Query([id], PrefixField(personPrefix, "rel"), false)
Timing('firstQuery', true)
```
This will produce a new metric: `transform.timing.firstQuery`.

add timings around batch steps.

---

internal/server/garbagecollector.go
internal/server/garbagecollector_test.go

Resolves Issue #28 
In this change, we signal the background go-routine that runs garbage collection to stop when the service is shut down. This is mostly to avoid big misleading stacktraces on shutdown.

Gracefully stop garbage collector on shutdown

---

internal/server/garbagecollector_test.go

The "stop gc" test was a little sensitive to timing problems. When running the test with a single cpu ( `go test -v ./... -cpu 1 -count 1 -run TestGC` ) it quite consistently would panic with nil reference errors.
With this change, we no longer shut down the complete datahub as part of the test-case. instead we only send a stop signal to the garbagecollector (same happens in fx OnStop lifecycle handler). This reduces the risk of timing problems.

improve robustness of gc test

---

Dockerfile
go.mod
go.sum

upgraded to latest release of badger from october. This should be backward compatible with binary badger layout.
removed cgo_enabled as the zstd datadog dep has now gone.

upgraded badger version and removed CGO_ENABLED

---

internal/security/login_provider.go

Added an else clause to prevent value from falling through and returning
empty ("") if found.
Closes #113

[113] FIX: Login provider returning empty string

---

DOCUMENTATION.md
internal/conf/config.go
internal/jobs/pipeline_history_test.go
internal/jobs/pipeline_test.go
internal/jobs/scheduler.go
internal/jobs/source/dataset_source.go
internal/jobs/source/dataset_source_test.go
internal/jobs/source/http_dataset_source.go
internal/jobs/source/multi_source.go
internal/jobs/source/multi_source_test.go
internal/jobs/source/sample_source.go
internal/jobs/source/slow_source.go
internal/server/dataset.go
internal/server/store_test.go
internal/web/datasethandler.go

when set to true, the data source will only emit changes that are the
"latest" version of the given entity. 
default remains that all changes are emitted.

new flag for datasetSource: LatestOnly

---

internal/jobs/source/dataset_source.go
internal/server/proxydataset.go
internal/web/datasethandler.go

Once an http response is written to, it's states code cannot be changed. Introducing the `preStream` hook allows webhandlers to delay the first writing to response so that more validation can happen beforehand

reorder response writing

---

internal/jobs/transform.go
internal/jobs/transform_test.go

If a transformation script in a job emits something other than Entity instances, datahub will now fail the job run with a descriptive error.

ignore invalid transform emissions

---

internal/server/dataset.go

when new entities are posted to a /dataset endpoint, incoming entities are parsed and validated. However, when new entities are produced via jobs there is no extra entity validation.
This fix handles the possible case that buggy job transforms produce nil references. I did not want to add general entity validation to transforms at this point because of performance.

return storage error when entities contain nil refs

---

internal/conf/logger.go

A Small change to the logger enables INFO, DEBUG, ERROR, WARN to be color coded and a little bit easier to read on the terminal.

Added small change to make logs more readable when running local

---

Makefile
go.mod
go.sum
internal/jobs/source/dataset_source.go
internal/jobs/source/union_source.go
internal/jobs/source/union_source_test.go
internal/security/claims.go
internal/security/login_provider_test.go
internal/security/manager.go
internal/security/manager_test.go
internal/server/badger_access.go
internal/server/proxydataset.go
internal/service/dataset/iterator.go
internal/service/dataset/iterator_benchmark_test.go
internal/service/dataset/iterator_test.go
internal/service/store/badger.go
internal/service/store/idx_keys.go
internal/testutil.go
internal/web/datasethandler.go
internal/web/securityhandler.go
security_integration_test.go

This change introduces the ability to list dataset changes in reverse order. 
closes issue #161. only partially (changes only, not entities)

reverse listing of changes

---

app.go
internal/server/badger_access.go
internal/service/dataset/iterator.go
internal/service/dataset/iterator_test.go
internal/service/entity/details.go
internal/service/entity/ids.go
internal/service/entity/ids_test.go
internal/service/namespace/manager.go
internal/service/store/badger.go
internal/service/store/idx_keys.go
internal/service/types/types.go
internal/web/datasethandler.go
internal/web/queryhandler.go

when flag is set, datahub will inject "datahub_details" as extra property into the resulting entity. this is useful for debugging and understanding how data evolved inside the datahub. "datahub_details" contains information about accessed datasets and change history per dataset.
the implementation is done in a separate module tree, service, and is likely to change when more functionality is moved to service modules. The idea is to replicate functionality in a more decoupled way, while still keeping the same performance levels.

add id-query flag "details"

---

go.mod
go.sum
internal/jobs/scheduler.go
internal/jobs/scheduler_test.go
internal/server/backup_test.go
internal/server/events_test.go
security_integration_test.go

This **should not be merged** until all datahub configs have been migrated to use job title.
Fixes #165

Make job title required for job configs

---

internal/conf/config.go
internal/conf/config_test.go
internal/conf/environment.go
internal/web/middleware.go
internal/web/middlewares/authentication.go

Support token validation against multiple issuers and audiences

---

internal/security/manager.go

After upgrading to golang-jwt v4, the default for marshalling single value audience claims is an array. According to https://www.rfc-editor.org/rfc/rfc7519#section-4.1.3 this may or may not be an array. Older versions of datahub expects this as a single value, so we want to change to default behaviour.

Don't marshal single audience string as array

---

go.mod
go.sum
internal/server/dataset_test.go
internal/server/get_related_test.go
internal/server/store.go
security_integration_test.go

when same relation was moved to different predicate in a change, outgoing queries would not always find all active relations. the added test is a case that previously would fail.

fix star-query bug

---

DOCUMENTATION.md
dataset_http_integration_test.go
internal/jobs/scheduler.go
internal/jobs/source/multi_source.go
internal/jobs/source/multi_source_dep_builder.go
internal/jobs/source/multi_source_dep_builder_test.go
internal/jobs/source/multi_source_test.go
internal/web/datasethandler.go

This change makes it possible to configure MultiSource from javascript. MultiSource looks for a function called `track_queries` in a jobs transform script, and provides a registy object as parameter when it calls this function.
job writers can then use `hop` and `iHop` on the starting object to add dependency configuration.
closes #235

configure multisource from javascript

---

internal/jobs/source/multi_source.go
internal/jobs/source/multi_source_test.go
internal/server/events_test.go

When the result of a dependency check exceeded the job batch size in the first ever processing of said dependency, this could lead to a panic

ensure incremental runs of multisource jobs dont panic

---

README.md
internal/server/store.go
internal/server/store_test.go

Issue: 173. Fixes transaction operation not updating dataset entity count

Fixes transaction operation not updating dataset entity count

---

internal/jobs/pipeline.go
internal/jobs/source/multi_source.go
internal/jobs/source/multi_source_test.go
internal/server/dataset.go

Solves #256 
- also avoid querying back in time when this is the first job run. this path should not be take when doing fullsync (which now is always the case with first runs) anyway, but for good measure.
- remove iterator instrumentation for performance

always do first multisource job run as fullsync

---

internal/jobs/job.go

This is to make sure we don't log "Finished" when a job has failed as this could be ambigous.
Added amount of processed entities in job-error log as well to help with debugging.

Moved Job Finished log in to job.success-check.

---

internal/service/entity/details.go

Fixes the details output from looking like this
```
"props": {
"datahub_details": {
"skifte.UnitType": {
"changes": [
"{\"id\":\"ns95:liter/bale\",\"internalId\":3108,\"recorded\":1694594182742072000,\"refs\":{\"ns2:type\":\"ns16:UnitType\",\"ns95:sameAs\":\"ns69:LITER_PER_BALE\"},\"props\":{\"ns95:name\":\"liter/bale\"}}"
],
"latest": "{\"id\":\"ns95:liter/bale\",\"internalId\":3108,\"recorded\":1694594182742072000,\"refs\":{\"ns2:type\":\"ns16:UnitType\",\"ns95:sameAs\":\"ns69:LITER_PER_BALE\"},\"props\":{\"ns95:name\":\"liter/bale\"}}"
}
```
to this:
```
"props": {
"datahub_details": {
"skifte.UnitType": {
"changes": [
{
"id": "ns95:liter/bale",
"internalId": 3108,
"props": {
"ns95:name": "liter/bale"
},
"recorded": 1694594182742072000,
"refs": {
"ns2:type": "ns16:UnitType", …
```

Fix entity details being escaped in query result

---

access_matrix_integration_test.go
internal/server/events_test.go
internal/web/middleware.go
internal/web/middlewares/authorization.go
internal/web/middlewares/opa.go

the previous implementation would not distinguish between authorizaton errors and underlying errors when chaining two middlewares. this unified implementation is able to do that.

do opa and acl in same middleware

---

internal/web/datasethandler.go

if users try to use the /entities endpoint of a dataset to consume the dataset incrementally, datahub now returns an error.

reject since parameter in entities request

---

internal/server/get_related_test.go
internal/server/store.go

Applies when doing queries with mergePartials set to false. This would cause a panic when a ref was pointing to a non existing entity.

Add check to handle missing related entity

---

internal/server/statistics.go

when retrieving stats for a single dataset, we dont want to scan all ref indexes to make the request faster. to see ref counts, one can still use the global /statistics endpoint

skip ref counts for dataset stats

---

Dockerfile

Since recent Docker versions [run build checks by default](https://docs.docker.com/build/checks/#build-with-checks) when building, we should fix this annoying warning when building the docker container
```
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)                                                                                                          0.0s
```

chore: fix FromAsCasing warning when building docker container

---

app.go
internal/server/garbagecollector.go
internal/server/statistics.go
internal/server/store.go
internal/service/scheduler/gc_update.go
internal/service/scheduler/schedulable.go
internal/service/scheduler/scheduler.go
internal/service/scheduler/statistics_update.go
internal/web/statisticshandler.go

since the gathering of badger stats can take a long time with larger data volumes, it is not practical to do the stat aggregation synchronously in an API request.
This change aggregagetes stats in a background job, once a day, and makes cached stats available in the API requests.
the garbage collector is now run regularly as well, and therefore https://github.com/mimiro-io/datahub/issues/1 is fully solved

move stats and gc to internal jobs

---

internal/service/scheduler/schedulable.go
internal/service/scheduler/statistics_update.go

also avoid possible overlapping maintenance job runs

Fix: avoid possible panic when ctx cancel is unavail

---

internal/jobs/transform.go
internal/jobs/transform_test.go
internal/server/dataset.go
internal/server/entity.go
internal/server/entity_test.go
internal/web/statisticshandler.go

Closes #315 
the new implementation is now correct for nested entities, number
values, array values. see entity_test.go for covered cases.
the new implementation is twice as fast when comparing entities with
only literal values, compared to the old impl. When arrays or nested
entities are encountered, it is comparably slower. but the old impl
would give a wrong result while being fast.
There is a benchmark test included in entity_test.go, which illustrates
the performance difference.

improved entity equality check when storing entities

---

internal/jobs/error_handler.go
internal/jobs/pipeline.go
internal/jobs/pipeline_history_test.go
internal/jobs/pipeline_test.go
internal/jobs/transform.go
internal/server/constants.go
internal/server/store.go

In this change, each transform instance uses its own copy of the `Store` struct. These contextual stores can be used to track information during the lifetime of a single transform, without introducing new parameters or other API changes.
The use case in this issue is to track which datasets are accessed from a transform script via queries or transactions.

introduce contextual store to track accessed datasets during transform

---

internal/server/store.go

Make sure we discard all badger transactions, as stated in comment here https://github.com/dgraph-io/badger/blob/master/txn.go#L780

Discard closed transaction

---

internal/jobs/scheduler.go
internal/jobs/scheduler_test.go
internal/web/joboperationhandler.go

closes #360 
the mim CLI should be updated to provide a job operation for calling this new endpoint

endpoint to reset job meta ( lineage data )
